package upinder.modelo;
// Generated 30-may-2016 18:03:24 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Comentario generated by hbm2java
 */
public class Comentario  implements java.io.Serializable {


     private Integer id;
     private Foto foto;
     private Usuario usuario;
     private String texto;
     private Date fechaPublicacion;

    public Comentario() {
    }

	
    public Comentario(Usuario usuario, String texto, Date fechaPublicacion) {
        this.usuario = usuario;
        this.texto = texto;
        this.fechaPublicacion = fechaPublicacion;
    }
    public Comentario(Foto foto, Usuario usuario, String texto, Date fechaPublicacion) {
       this.foto = foto;
       this.usuario = usuario;
       this.texto = texto;
       this.fechaPublicacion = fechaPublicacion;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Foto getFoto() {
        return this.foto;
    }
    
    public void setFoto(Foto foto) {
        this.foto = foto;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getTexto() {
        return this.texto;
    }
    
    public void setTexto(String texto) {
        this.texto = texto;
    }
    public Date getFechaPublicacion() {
        return this.fechaPublicacion;
    }
    
    public void setFechaPublicacion(Date fechaPublicacion) {
        this.fechaPublicacion = fechaPublicacion;
    }




}


