package upinder.modelo;
// Generated 30-may-2016 18:03:24 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Denuncia generated by hbm2java
 */
public class Denuncia  implements java.io.Serializable {


     private Integer id;
     private TipoDenuncia tipoDenuncia;
     private Usuario usuarioByUsuario;
     private Usuario usuarioByDenunciado;
     private String declaracion;
     private Date fechaDenuncia;

    public Denuncia() {
    }

    public Denuncia(TipoDenuncia tipoDenuncia, Usuario usuarioByUsuario, Usuario usuarioByDenunciado, String declaracion, Date fechaDenuncia) {
       this.tipoDenuncia = tipoDenuncia;
       this.usuarioByUsuario = usuarioByUsuario;
       this.usuarioByDenunciado = usuarioByDenunciado;
       this.declaracion = declaracion;
       this.fechaDenuncia = fechaDenuncia;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public TipoDenuncia getTipoDenuncia() {
        return this.tipoDenuncia;
    }
    
    public void setTipoDenuncia(TipoDenuncia tipoDenuncia) {
        this.tipoDenuncia = tipoDenuncia;
    }
    public Usuario getUsuarioByUsuario() {
        return this.usuarioByUsuario;
    }
    
    public void setUsuarioByUsuario(Usuario usuarioByUsuario) {
        this.usuarioByUsuario = usuarioByUsuario;
    }
    public Usuario getUsuarioByDenunciado() {
        return this.usuarioByDenunciado;
    }
    
    public void setUsuarioByDenunciado(Usuario usuarioByDenunciado) {
        this.usuarioByDenunciado = usuarioByDenunciado;
    }
    public String getDeclaracion() {
        return this.declaracion;
    }
    
    public void setDeclaracion(String declaracion) {
        this.declaracion = declaracion;
    }
    public Date getFechaDenuncia() {
        return this.fechaDenuncia;
    }
    
    public void setFechaDenuncia(Date fechaDenuncia) {
        this.fechaDenuncia = fechaDenuncia;
    }




}


