package upinder.modelo;
// Generated 30-may-2016 18:03:24 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Foto generated by hbm2java
 */
public class Foto  implements java.io.Serializable {


     private Integer id;
     private Usuario usuario;
     private String titulo;
     private String url;
     private boolean dePerfil;
     private Set reaccions = new HashSet(0);
     private Set comentarios = new HashSet(0);
     private Set notificacions = new HashSet(0);

    public Foto() {
    }

	
    public Foto(Usuario usuario, String titulo, String url, boolean dePerfil) {
        this.usuario = usuario;
        this.titulo = titulo;
        this.url = url;
        this.dePerfil = dePerfil;
    }
    public Foto(Usuario usuario, String titulo, String url, boolean dePerfil, Set reaccions, Set comentarios, Set notificacions) {
       this.usuario = usuario;
       this.titulo = titulo;
       this.url = url;
       this.dePerfil = dePerfil;
       this.reaccions = reaccions;
       this.comentarios = comentarios;
       this.notificacions = notificacions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public boolean isDePerfil() {
        return this.dePerfil;
    }
    
    public void setDePerfil(boolean dePerfil) {
        this.dePerfil = dePerfil;
    }
    public Set getReaccions() {
        return this.reaccions;
    }
    
    public void setReaccions(Set reaccions) {
        this.reaccions = reaccions;
    }
    public Set getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(Set comentarios) {
        this.comentarios = comentarios;
    }
    public Set getNotificacions() {
        return this.notificacions;
    }
    
    public void setNotificacions(Set notificacions) {
        this.notificacions = notificacions;
    }




}


