package upinder.modelo;
// Generated 30-may-2016 18:03:24 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Interaccion generated by hbm2java
 */
public class Interaccion  implements java.io.Serializable {


     private Integer id;
     private Usuario usuarioByEmisor;
     private Usuario usuarioByReceptor;
     private String tipo;
     private Date fecha;

    public Interaccion() {
    }

    public Interaccion(Usuario usuarioByEmisor, Usuario usuarioByReceptor, String tipo, Date fecha) {
       this.usuarioByEmisor = usuarioByEmisor;
       this.usuarioByReceptor = usuarioByReceptor;
       this.tipo = tipo;
       this.fecha = fecha;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Usuario getUsuarioByEmisor() {
        return this.usuarioByEmisor;
    }
    
    public void setUsuarioByEmisor(Usuario usuarioByEmisor) {
        this.usuarioByEmisor = usuarioByEmisor;
    }
    public Usuario getUsuarioByReceptor() {
        return this.usuarioByReceptor;
    }
    
    public void setUsuarioByReceptor(Usuario usuarioByReceptor) {
        this.usuarioByReceptor = usuarioByReceptor;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


