package upinder.modelo;
// Generated 30-may-2016 18:03:24 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Match generated by hbm2java
 */
public class Match  implements java.io.Serializable {


     private Integer id;
     private Usuario usuarioByUsuario1;
     private Usuario usuarioByUsuario2;
     private Date fecha;

    public Match() {
    }

    public Match(Usuario usuarioByUsuario1, Usuario usuarioByUsuario2, Date fecha) {
       this.usuarioByUsuario1 = usuarioByUsuario1;
       this.usuarioByUsuario2 = usuarioByUsuario2;
       this.fecha = fecha;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Usuario getUsuarioByUsuario1() {
        return this.usuarioByUsuario1;
    }
    
    public void setUsuarioByUsuario1(Usuario usuarioByUsuario1) {
        this.usuarioByUsuario1 = usuarioByUsuario1;
    }
    public Usuario getUsuarioByUsuario2() {
        return this.usuarioByUsuario2;
    }
    
    public void setUsuarioByUsuario2(Usuario usuarioByUsuario2) {
        this.usuarioByUsuario2 = usuarioByUsuario2;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


