package upinder.modelo;
// Generated 30-may-2016 18:03:24 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Mensaje generated by hbm2java
 */
public class Mensaje  implements java.io.Serializable {


     private Integer id;
     private Usuario usuarioByEmisor;
     private Usuario usuarioByReceptor;
     private String texto;
     private Date fechaEnvio;
     private Date fechaLectura;

    public Mensaje() {
    }

	
    public Mensaje(Usuario usuarioByEmisor, Usuario usuarioByReceptor, String texto, Date fechaEnvio) {
        this.usuarioByEmisor = usuarioByEmisor;
        this.usuarioByReceptor = usuarioByReceptor;
        this.texto = texto;
        this.fechaEnvio = fechaEnvio;
    }
    public Mensaje(Usuario usuarioByEmisor, Usuario usuarioByReceptor, String texto, Date fechaEnvio, Date fechaLectura) {
       this.usuarioByEmisor = usuarioByEmisor;
       this.usuarioByReceptor = usuarioByReceptor;
       this.texto = texto;
       this.fechaEnvio = fechaEnvio;
       this.fechaLectura = fechaLectura;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Usuario getUsuarioByEmisor() {
        return this.usuarioByEmisor;
    }
    
    public void setUsuarioByEmisor(Usuario usuarioByEmisor) {
        this.usuarioByEmisor = usuarioByEmisor;
    }
    public Usuario getUsuarioByReceptor() {
        return this.usuarioByReceptor;
    }
    
    public void setUsuarioByReceptor(Usuario usuarioByReceptor) {
        this.usuarioByReceptor = usuarioByReceptor;
    }
    public String getTexto() {
        return this.texto;
    }
    
    public void setTexto(String texto) {
        this.texto = texto;
    }
    public Date getFechaEnvio() {
        return this.fechaEnvio;
    }
    
    public void setFechaEnvio(Date fechaEnvio) {
        this.fechaEnvio = fechaEnvio;
    }
    public Date getFechaLectura() {
        return this.fechaLectura;
    }
    
    public void setFechaLectura(Date fechaLectura) {
        this.fechaLectura = fechaLectura;
    }




}


