package upinder.modelo;
// Generated 30-may-2016 18:03:24 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Notificacion generated by hbm2java
 */
public class Notificacion  implements java.io.Serializable {


     private Integer id;
     private Foto foto;
     private Usuario usuarioByUsuarioAux;
     private Usuario usuarioByUsuario;
     private String tipo;
     private String texto;
     private Date fechaCreacion;
     private Date fechaLectura;

    public Notificacion() {
    }

	
    public Notificacion(Usuario usuarioByUsuario, String tipo, String texto, Date fechaCreacion) {
        this.usuarioByUsuario = usuarioByUsuario;
        this.tipo = tipo;
        this.texto = texto;
        this.fechaCreacion = fechaCreacion;
    }
    public Notificacion(Foto foto, Usuario usuarioByUsuarioAux, Usuario usuarioByUsuario, String tipo, String texto, Date fechaCreacion, Date fechaLectura) {
       this.foto = foto;
       this.usuarioByUsuarioAux = usuarioByUsuarioAux;
       this.usuarioByUsuario = usuarioByUsuario;
       this.tipo = tipo;
       this.texto = texto;
       this.fechaCreacion = fechaCreacion;
       this.fechaLectura = fechaLectura;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Foto getFoto() {
        return this.foto;
    }
    
    public void setFoto(Foto foto) {
        this.foto = foto;
    }
    public Usuario getUsuarioByUsuarioAux() {
        return this.usuarioByUsuarioAux;
    }
    
    public void setUsuarioByUsuarioAux(Usuario usuarioByUsuarioAux) {
        this.usuarioByUsuarioAux = usuarioByUsuarioAux;
    }
    public Usuario getUsuarioByUsuario() {
        return this.usuarioByUsuario;
    }
    
    public void setUsuarioByUsuario(Usuario usuarioByUsuario) {
        this.usuarioByUsuario = usuarioByUsuario;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getTexto() {
        return this.texto;
    }
    
    public void setTexto(String texto) {
        this.texto = texto;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaLectura() {
        return this.fechaLectura;
    }
    
    public void setFechaLectura(Date fechaLectura) {
        this.fechaLectura = fechaLectura;
    }




}


