package upinder.modelo;
// Generated 30-may-2016 18:03:24 by Hibernate Tools 4.3.1



/**
 * Reaccion generated by hbm2java
 */
public class Reaccion  implements java.io.Serializable {


     private Integer id;
     private Foto foto;
     private Usuario usuario;
     private Integer publicacion;

    public Reaccion() {
    }

	
    public Reaccion(Usuario usuario) {
        this.usuario = usuario;
    }
    public Reaccion(Foto foto, Usuario usuario, Integer publicacion) {
       this.foto = foto;
       this.usuario = usuario;
       this.publicacion = publicacion;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Foto getFoto() {
        return this.foto;
    }
    
    public void setFoto(Foto foto) {
        this.foto = foto;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Integer getPublicacion() {
        return this.publicacion;
    }
    
    public void setPublicacion(Integer publicacion) {
        this.publicacion = publicacion;
    }




}


