package upinder.modelo;
// Generated 30-may-2016 18:03:24 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoDenuncia generated by hbm2java
 */
public class TipoDenuncia  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set denuncias = new HashSet(0);

    public TipoDenuncia() {
    }

	
    public TipoDenuncia(String nombre) {
        this.nombre = nombre;
    }
    public TipoDenuncia(String nombre, Set denuncias) {
       this.nombre = nombre;
       this.denuncias = denuncias;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getDenuncias() {
        return this.denuncias;
    }
    
    public void setDenuncias(Set denuncias) {
        this.denuncias = denuncias;
    }




}


