package upinder.modelo;
// Generated 30-may-2016 18:03:24 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoSexo generated by hbm2java
 */
public class TipoSexo  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set usuariosForQueBusca = new HashSet(0);
     private Set usuariosForSexo = new HashSet(0);

    public TipoSexo() {
    }

	
    public TipoSexo(String nombre) {
        this.nombre = nombre;
    }
    public TipoSexo(String nombre, Set usuariosForQueBusca, Set usuariosForSexo) {
       this.nombre = nombre;
       this.usuariosForQueBusca = usuariosForQueBusca;
       this.usuariosForSexo = usuariosForSexo;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getUsuariosForQueBusca() {
        return this.usuariosForQueBusca;
    }
    
    public void setUsuariosForQueBusca(Set usuariosForQueBusca) {
        this.usuariosForQueBusca = usuariosForQueBusca;
    }
    public Set getUsuariosForSexo() {
        return this.usuariosForSexo;
    }
    
    public void setUsuariosForSexo(Set usuariosForSexo) {
        this.usuariosForSexo = usuariosForSexo;
    }




}


