package upinder.modelo;
// Generated 30-may-2016 18:03:24 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Titulacion generated by hbm2java
 */
public class Titulacion  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set usuarios = new HashSet(0);

    public Titulacion() {
    }

	
    public Titulacion(String nombre) {
        this.nombre = nombre;
    }
    public Titulacion(String nombre, Set usuarios) {
       this.nombre = nombre;
       this.usuarios = usuarios;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


