package upinder.modelo;
// Generated 30-may-2016 18:03:24 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer id;
     private TipoSexo tipoSexoByQueBusca;
     private TipoSexo tipoSexoBySexo;
     private Titulacion titulacion;
     private String password;
     private String email;
     private String nombre;
     private String apellidos;
     private Date fechanac;
     private String fotoPerfil;
     private boolean emailNot;
     private Date fechaalta;
     private String codAct;
     private boolean activado;
     private Set mensajesForEmisor = new HashSet(0);
     private Set matchesForUsuario1 = new HashSet(0);
     private Set notificacionsForUsuarioAux = new HashSet(0);
     private Set matchesForUsuario2 = new HashSet(0);
     private Set fotos = new HashSet(0);
     private Set comentarios = new HashSet(0);
     private Set reaccions = new HashSet(0);
     private Set denunciasForUsuario = new HashSet(0);
     private Set interaccionsForEmisor = new HashSet(0);
     private Set notificacionsForUsuario = new HashSet(0);
     private Set interaccionsForReceptor = new HashSet(0);
     private Set mensajesForReceptor = new HashSet(0);
     private Set denunciasForDenunciado = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(TipoSexo tipoSexoByQueBusca, TipoSexo tipoSexoBySexo, Titulacion titulacion, String password, String email, String nombre, String apellidos, Date fechanac, boolean emailNot, Date fechaalta, String codAct, boolean activado) {
        this.tipoSexoByQueBusca = tipoSexoByQueBusca;
        this.tipoSexoBySexo = tipoSexoBySexo;
        this.titulacion = titulacion;
        this.password = password;
        this.email = email;
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.fechanac = fechanac;
        this.emailNot = emailNot;
        this.fechaalta = fechaalta;
        this.codAct = codAct;
        this.activado = activado;
    }
    public Usuario(TipoSexo tipoSexoByQueBusca, TipoSexo tipoSexoBySexo, Titulacion titulacion, String password, String email, String nombre, String apellidos, Date fechanac, String fotoPerfil, boolean emailNot, Date fechaalta, String codAct, boolean activado, Set mensajesForEmisor, Set matchesForUsuario1, Set notificacionsForUsuarioAux, Set matchesForUsuario2, Set fotos, Set comentarios, Set reaccions, Set denunciasForUsuario, Set interaccionsForEmisor, Set notificacionsForUsuario, Set interaccionsForReceptor, Set mensajesForReceptor, Set denunciasForDenunciado) {
       this.tipoSexoByQueBusca = tipoSexoByQueBusca;
       this.tipoSexoBySexo = tipoSexoBySexo;
       this.titulacion = titulacion;
       this.password = password;
       this.email = email;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.fechanac = fechanac;
       this.fotoPerfil = fotoPerfil;
       this.emailNot = emailNot;
       this.fechaalta = fechaalta;
       this.codAct = codAct;
       this.activado = activado;
       this.mensajesForEmisor = mensajesForEmisor;
       this.matchesForUsuario1 = matchesForUsuario1;
       this.notificacionsForUsuarioAux = notificacionsForUsuarioAux;
       this.matchesForUsuario2 = matchesForUsuario2;
       this.fotos = fotos;
       this.comentarios = comentarios;
       this.reaccions = reaccions;
       this.denunciasForUsuario = denunciasForUsuario;
       this.interaccionsForEmisor = interaccionsForEmisor;
       this.notificacionsForUsuario = notificacionsForUsuario;
       this.interaccionsForReceptor = interaccionsForReceptor;
       this.mensajesForReceptor = mensajesForReceptor;
       this.denunciasForDenunciado = denunciasForDenunciado;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public TipoSexo getTipoSexoByQueBusca() {
        return this.tipoSexoByQueBusca;
    }
    
    public void setTipoSexoByQueBusca(TipoSexo tipoSexoByQueBusca) {
        this.tipoSexoByQueBusca = tipoSexoByQueBusca;
    }
    public TipoSexo getTipoSexoBySexo() {
        return this.tipoSexoBySexo;
    }
    
    public void setTipoSexoBySexo(TipoSexo tipoSexoBySexo) {
        this.tipoSexoBySexo = tipoSexoBySexo;
    }
    public Titulacion getTitulacion() {
        return this.titulacion;
    }
    
    public void setTitulacion(Titulacion titulacion) {
        this.titulacion = titulacion;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public Date getFechanac() {
        return this.fechanac;
    }
    
    public void setFechanac(Date fechanac) {
        this.fechanac = fechanac;
    }
    public String getFotoPerfil() {
        return this.fotoPerfil;
    }
    
    public void setFotoPerfil(String fotoPerfil) {
        this.fotoPerfil = fotoPerfil;
    }
    public boolean isEmailNot() {
        return this.emailNot;
    }
    
    public void setEmailNot(boolean emailNot) {
        this.emailNot = emailNot;
    }
    public Date getFechaalta() {
        return this.fechaalta;
    }
    
    public void setFechaalta(Date fechaalta) {
        this.fechaalta = fechaalta;
    }
    public String getCodAct() {
        return this.codAct;
    }
    
    public void setCodAct(String codAct) {
        this.codAct = codAct;
    }
    public boolean isActivado() {
        return this.activado;
    }
    
    public void setActivado(boolean activado) {
        this.activado = activado;
    }
    public Set getMensajesForEmisor() {
        return this.mensajesForEmisor;
    }
    
    public void setMensajesForEmisor(Set mensajesForEmisor) {
        this.mensajesForEmisor = mensajesForEmisor;
    }
    public Set getMatchesForUsuario1() {
        return this.matchesForUsuario1;
    }
    
    public void setMatchesForUsuario1(Set matchesForUsuario1) {
        this.matchesForUsuario1 = matchesForUsuario1;
    }
    public Set getNotificacionsForUsuarioAux() {
        return this.notificacionsForUsuarioAux;
    }
    
    public void setNotificacionsForUsuarioAux(Set notificacionsForUsuarioAux) {
        this.notificacionsForUsuarioAux = notificacionsForUsuarioAux;
    }
    public Set getMatchesForUsuario2() {
        return this.matchesForUsuario2;
    }
    
    public void setMatchesForUsuario2(Set matchesForUsuario2) {
        this.matchesForUsuario2 = matchesForUsuario2;
    }
    public Set getFotos() {
        return this.fotos;
    }
    
    public void setFotos(Set fotos) {
        this.fotos = fotos;
    }
    public Set getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(Set comentarios) {
        this.comentarios = comentarios;
    }
    public Set getReaccions() {
        return this.reaccions;
    }
    
    public void setReaccions(Set reaccions) {
        this.reaccions = reaccions;
    }
    public Set getDenunciasForUsuario() {
        return this.denunciasForUsuario;
    }
    
    public void setDenunciasForUsuario(Set denunciasForUsuario) {
        this.denunciasForUsuario = denunciasForUsuario;
    }
    public Set getInteraccionsForEmisor() {
        return this.interaccionsForEmisor;
    }
    
    public void setInteraccionsForEmisor(Set interaccionsForEmisor) {
        this.interaccionsForEmisor = interaccionsForEmisor;
    }
    public Set getNotificacionsForUsuario() {
        return this.notificacionsForUsuario;
    }
    
    public void setNotificacionsForUsuario(Set notificacionsForUsuario) {
        this.notificacionsForUsuario = notificacionsForUsuario;
    }
    public Set getInteraccionsForReceptor() {
        return this.interaccionsForReceptor;
    }
    
    public void setInteraccionsForReceptor(Set interaccionsForReceptor) {
        this.interaccionsForReceptor = interaccionsForReceptor;
    }
    public Set getMensajesForReceptor() {
        return this.mensajesForReceptor;
    }
    
    public void setMensajesForReceptor(Set mensajesForReceptor) {
        this.mensajesForReceptor = mensajesForReceptor;
    }
    public Set getDenunciasForDenunciado() {
        return this.denunciasForDenunciado;
    }
    
    public void setDenunciasForDenunciado(Set denunciasForDenunciado) {
        this.denunciasForDenunciado = denunciasForDenunciado;
    }




}


